apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-secret
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.databaseUrl }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc | quote }}
  {{- else }}
  DATABASE_URL: ""
  {{- end }}
  {{- if .Values.secret.geminiApiKey }}
  GEMINI_API_KEY: {{ .Values.secret.geminiApiKey | b64enc | quote }}
  {{- else }}
  GEMINI_API_KEY: ""
  {{- end }}
  {{- if .Values.secret.jwtSecretKey }}
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | b64enc | quote }}
  {{- else }}
  JWT_SECRET_KEY: ""
  {{- end }}
  {{- if .Values.secret.neonApiKey }}
  NEON_API_KEY: {{ .Values.secret.neonApiKey | b64enc | quote }}
  {{- else }}
  NEON_API_KEY: ""
  {{- end }}
